version: '3.7'   
services:
  web:      
    image: node    
    working_dir: /app
    command: npm start
    volumes:
      - ../:/app      
    ports:
      - "3000:3000"    
    depends_on:
      - tasks_postgresql 
    environment:               
      DATABASE_URL: postgres://adminTasks:pgpassword@tasks_postgresql:5432/tasks  
  tasks_postgresql:
    image: postgres:11.4
    environment:
      - POSTGRES_USER=adminTasks
      - POSTGRES_PASSWORD=pgpassword
      - POSTGRES_DB=tasks          
    ports:
     - "5432:5432"
      
